title: Ilenna Jones
description: Homepage of Ilenna Jones
author: Ilenna Jones
github: https://github.com/ilennaj
about: I am a Neuroscience PhD Candidate at the University of Pennsylvania working in the Kording Lab.
disqus_shortname: ilennaj-github-io
google_analytics: UA-XXXXXXXX-Y

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "#"
    - icon: fa-twitter
      link: "#"
    - icon: fa-linkedin
      link: "#"
    - icon: fa-stack-exchange
      link: "#"
    - icon: fa-github
      link: "https://github.com/ilennaj"

share:
  twitter_username: ilennaj
  fb_appid: 

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://ilennaj.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
